version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1@Zubrig
    ports:
      - "3306:3306"
    volumes:
      - /path/to/your/mysql/data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile  # Especifica o Dockerfile do aplicativo
    container_name: app-container
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 1@Zubrig
