-- CreateTable
CREATE TABLE `Acesso` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `datahora` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `userId` INTEGER NOT NULL,
    `entrada` BOOLEAN NOT NULL,
    `saida` BOOLEAN NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Acesso` ADD CONSTRAINT `Acesso_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
